name: Crosslinker / Go - Build

on: [pull_request]

defaults:
  run:
    working-directory: crosslinker

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19', '1.20']
    steps:
      - uses: actions/checkout@v3
      - name: Build with Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go build ./...
