name:  Crosslinker / Go - Lint

on: [pull_request]

defaults:
  run:
    working-directory: crosslinker

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22']
    steps:
      - uses: actions/checkout@v4
      - name: Lint in Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go vet
