name: NPM / TypeScript - Build

on: [pull_request]

defaults:
  run:
    working-directory: npm-module

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v5
    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --production=false
    - run: yarn build
      env:
        CI: true
